name: Test Basic Workflow

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Basic Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "Workflow is working!"
